version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: raw data source from greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales data of greenweez

      - name: product
        columns:
          - name: products_id
            description: PK of product table
            tests:
              - not_null
              - unique
      - name: ship
        columns:
          - name: orders_id
            tests:
              - not_null
              - unique
